"""Type stubs for the Rust extension `binary_embedding._native`.

Generated by hand to match `src/lib.rs`. Keep in sync.
"""

from __future__ import annotations

__version__: str

# ---------------------------------------------------------------------------
# Sampling
# ---------------------------------------------------------------------------

def file_size(path: str) -> int: ...
def read_head(path: str, n: int) -> bytes: ...
def read_tail(path: str, n: int) -> bytes: ...
def read_window(path: str, offset: int, n: int) -> bytes: ...
def read_strided_chunks(path: str, n_chunks: int, chunk_size: int) -> list[bytes]: ...
def read_random_window(path: str, window: int, seed: int) -> tuple[int, bytes]: ...
def read_random_windows(
    path: str, n_windows: int, window: int, seed: int
) -> list[tuple[int, bytes]]: ...
def read_paths_to_file_as_bytes(
    paths: list[str],
    output_path: str,
    byte_offset: int,
    chunk_files: int = 64,
    max_bytes: int | None = None,
) -> list[tuple[int, int, int]]:
    """Stream-read `paths`, shift each byte by `byte_offset`, write u16 LE to disk.

    Used to build the byte-variant cache. Returns `(offset_in_elements,
    n_tokens, n_bytes)` per path in input order. The streamed file matches the
    layout produced by `tokenize_paths_to_file(dtype="u16")`.
    """
    ...

# ---------------------------------------------------------------------------
# Tokenization
# ---------------------------------------------------------------------------

class BinaryTokenizer:
    @staticmethod
    def from_file(path: str) -> "BinaryTokenizer": ...

    @property
    def vocab_size(self) -> int: ...
    def encode(self, data: bytes, add_special_tokens: bool = False) -> list[int]: ...
    def encode_batch(
        self, data: list[bytes], add_special_tokens: bool = False
    ) -> list[list[int]]: ...
    def decode(self, ids: list[int], skip_special_tokens: bool = True) -> bytes: ...
    def round_trip(self, data: bytes) -> bool: ...

def tokenize_paths(
    tokenizer: BinaryTokenizer,
    paths: list[str],
    max_bytes: int | None = None,
    add_special_tokens: bool = False,
) -> list[list[int]]: ...
def tokenize_paths_to_file(
    tokenizer: BinaryTokenizer,
    paths: list[str],
    output_path: str,
    dtype: str = "u16",
    chunk_files: int = 64,
    max_bytes: int | None = None,
    add_special_tokens: bool = False,
) -> list[tuple[int, int, int]]:
    """Stream-encode `paths` to a packed binary at `output_path`.

    Returns an index list of `(offset, n_tokens, n_bytes)` per file, in input
    order. `offset` is the element index into the output stream (multiply by 2
    for u16 / 4 for u32 to get a byte offset). The packed stream itself is
    little-endian, no header — memory-map it on the read side.
    """
    ...

# ---------------------------------------------------------------------------
# MLM and window sampling
# ---------------------------------------------------------------------------

def sample_token_window(
    tokens: list[int], seq_len: int, pad_id: int, seed: int
) -> tuple[list[int], list[int]]: ...
def sample_token_windows(
    tokens: list[int], seq_len: int, n_windows: int, pad_id: int, seed: int
) -> tuple[list[list[int]], list[list[int]]]: ...
def mlm_mask(
    input_ids: list[int],
    special_ids: list[int],
    mask_id: int,
    vocab_size: int,
    first_real_id: int,
    mask_ratio: float,
    seed: int,
    keep_random_split: tuple[float, float, float] = (0.8, 0.1, 0.1),
) -> tuple[list[int], list[int]]: ...
def mlm_mask_many(
    batch_input_ids: list[list[int]],
    special_ids: list[int],
    mask_id: int,
    vocab_size: int,
    first_real_id: int,
    mask_ratio: float,
    base_seed: int,
    keep_random_split: tuple[float, float, float] = (0.8, 0.1, 0.1),
) -> tuple[list[list[int]], list[list[int]]]:
    """Batched form of `mlm_mask` — one PyO3 call, rayon-parallel across rows."""
    ...
